name: .NET Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2.4.2
    - uses: nuget/setup-nuget@v1.0.6
    - name: Build
      run: dotnet build --configuration Release
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - name: Create Release
      id: create_release
      uses: "marvinpinto/action-automatic-releases@v1.2.1"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: Release ${{ github.sha }}
        files: ./Whisker/bin/Release/Whisker.exe
        prerelease: false
